# Generated by Django 5.1.3 on 2024-11-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('space1', models.CharField(blank=True, max_length=255, null=True)),
                ('space2', models.CharField(blank=True, max_length=255, null=True)),
                ('space3', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
